name: Deploy to dev environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-dev-environment:
      runs-on: ubuntu-latest
      environment: dev
      steps:
          - uses: actions/setup-node@v3
            with:
              node-version: '18'
          - name: 'Checkout source code'
            uses: actions/checkout@v4
            with:
              fetch-depth: '2'
                
          # Now Install Salesforce CLI
          - name: 'Install SF CLI'
            run: npm install @salesforce/cli --global
          - name: 'Installing sfdx git delta'
            run: | 
                echo Y | sf plugins:install sfdx-git-delta
                sf plugins

          - name: 'Create delta packages'
            run: | 
              mkdir changed-sources
              sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
              echo "[INFO] Diff generated"
                
          - name: 'Run all local tests'
            run: |
                echo "${{ secrets.SF_JWT_KEY }}" > server.key
                sf org login jwt --username ${{ secrets.SF_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.SF_CONSUMER_KEY }} --instance-url ${{ vars.INSTANCE_URL }} --set-default
                sf apex run test --test-level RunLocalTests --result-format human
